apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dotnet-api-chart.fullname" . }}
  labels: {{- include "dotnet-api-chart.labels" . | nindent 4 }}
data:
  appsettings.json: |
{{- .Values.appsettings.content | nindent 4 }}