apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications-dev
  namespace: argocd
  labels:
    app: applications-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/fchanteau/starter-app-gitops
    targetRevision: HEAD
    path: apps # Directory containing child app definitions
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # Parent deploys children to argocd namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - Delete=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
