image:
  repository: fchanteau95/starter-app
  tag: feat-config.3044e04
replicaCount: 1
# do this command to access via browser : minikube service -n ingress-nginx ingress-nginx-controller --url
ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: ""
      paths:
        - path: /app1(/|$)(.*)
          pathType: ImplementationSpecific

custom:
  applicationName: app-1
  env: devci

appsettings:
  content: |
    {{ tpl (.Files.Get (printf "%s/%s/appsettings.json" .Values.custom.applicationName .Values.custom.env)) . | nindent 4 }}
