image:
  repository: fchanteau95/starter-app
  tag: latest
replicaCount: 1

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  className: ""
  annotations: {}
  hosts:
    - paths:
        - path: /app1
          pathType: Prefix
  tls: []

service:
  type: LoadBalancer
  port: 80

containerPort: 8080
