image:
  repository: fchanteau95/starter-app
  tag: latest
replicaCount: 1

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: ""
      paths:
        - path: /app1(/|$)(.*)
          pathType: ImplementationSpecific
  tls: []

service:
  type: ClusterIP
  port: 80

containerPort: 8080
