image:
  repository: fchanteau95/starter-app
  tag: feat-config.4048dc9
replicaCount: 1
# do this command to access via browser : minikube service -n ingress-nginx ingress-nginx-controller --url
ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: ""
      paths:
        - path: /app1(/|$)(.*)
          pathType: ImplementationSpecific
  tls: []

service:
  type: ClusterIP
  port: 80

containerPort: 8080

custom:
  applicationName: app-1
  env: devci

appsettings:
  content: |
  {
    "Logging": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft.AspNetCore": "Warning"
      }
    },
    "ConfigSection": {
      "Value": "I am in Development from Helm configuration"
    }
  }
