image:
  repository: fchanteau95/starter-app
  tag: latest
replicaCount: 1

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /app1
          pathType: Prefix
  tls: []

service:
  type: ClusterIP
  port: 80

containerPort: 8080
